version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: sleep infinity
    image: factate_backend_dev
    volumes:
      - ./backend:/app/src
      - backend_venv:/app/env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: sleep infinity
    environment:
      - CHOKIDAR_USEPOLLING=true
    image: factate_frontend_dev
    ports:
      - 3000
    volumes:
      - ./frontend:/app/src
volumes:
  backend_venv: {}
