version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: dofa_backend_dev
    volumes:
      - ./backend:/app/src
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: sleep infinity
    environment:
      - CHOKIDAR_USEPOLLING=true
    image: dofa_frontend_dev
    ports:
      - 3000
    volumes:
      - ./frontend:/app/src
