FROM python:3

# install pkg dependencies
RUN apt-get update && apt-get install -y \
    make

# install dev pkg dependencies
RUN apt-get update && apt-get install -y \
    curl \
    fish \
    nano

WORKDIR /app/src